### ISSUE TITLE
finish milestone 1 deliverable

### ISSUE THREAD

**Issue by shifdub** [picme-gallery/picme-gallery.github.io#1]
* [ ] Create data model implementation page with links to entity classes
* [ ] Review ERD
* [ ] Review entity classes
* [ ] Update exported ERD files
